# Generated by Django 3.2.8 on 2021-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211024_1008'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='data_groups', to='core.DataGroup', verbose_name='data groups'),
        ),
    ]
