# Generated by Django 3.2.8 on 2021-10-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211024_1124'),
        ('security', '0002_user_data_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_groups',
            field=models.ManyToManyField(blank=True, related_name='data_groups', to='core.DataGroup', verbose_name='data groups'),
        ),
    ]
