# Generated by Django 3.2.8 on 2023-04-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_user_data_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_groups',
        ),
    ]
