# Generated by Django 3.2.8 on 2021-10-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211023_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronizedtables',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='synchronizedtables',
            name='lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
