# Generated by Django 3.2.8 on 2021-10-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_relationstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchronizedtables',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='synchronizedtables',
            name='lon',
        ),
        migrations.AddField(
            model_name='synchronizedtables',
            name='property_latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='property latitude'),
        ),
        migrations.AddField(
            model_name='synchronizedtables',
            name='property_longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='property longitude'),
        ),
    ]
