# Generated by Django 3.2.8 on 2021-10-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_datagroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronizedtables',
            name='alias',
            field=models.CharField(max_length=255, unique=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='synchronizedtables',
            name='table',
            field=models.CharField(max_length=100, unique=True, verbose_name='table'),
        ),
    ]
