# Generated by Django 3.2.8 on 2021-10-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211024_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchronizedtables',
            name='alias',
            field=models.CharField(max_length=255, verbose_name='alias'),
        ),
    ]
