# Generated by Django 3.2.8 on 2022-06-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_alter_connection_periodic_task'),
        ('core', '0012_synchronizedtables_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizedtables',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.connection', verbose_name='connection'),
        ),
    ]
