# Generated by Django 3.2.8 on 2022-08-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_synchronizedtables_property_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizedtables',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='synchronizedtables',
            name='relation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.relationstable', verbose_name='relation'),
        ),
    ]
