# Generated by Django 3.2.8 on 2022-09-14 02:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_synchronizedtables_table_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchronizedtables',
            name='data',
        ),
        migrations.CreateModel(
            name='SynchronizedTablesData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('data', models.JSONField(default=dict)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.synchronizedtables', verbose_name='table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
