# Generated by Django 3.2.8 on 2022-11-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_synchronizedtablesdata_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchronizedtables',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='synchronizedtables',
            name='show_on_map',
        ),
        migrations.RemoveField(
            model_name='synchronizedtables',
            name='table_geo',
        ),
    ]
