# Generated by Django 3.2.8 on 2022-11-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20221104_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizedtablesdata',
            name='relations',
            field=models.ManyToManyField(related_name='relations', to='core.RelationsTable', verbose_name='relations'),
        ),
    ]
