# Generated by Django 3.2.8 on 2022-11-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_relationstable_two_dimensional'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizedtables',
            name='relations',
            field=models.ManyToManyField(related_name='relations', to='core.RelationsTable', verbose_name='relations'),
        ),
        migrations.DeleteModel(
            name='SynchronizedTablesData',
        ),
    ]
