# Generated by Django 3.2.8 on 2022-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20221104_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizedtables',
            name='sql',
            field=models.TextField(blank=True, null=True),
        ),
    ]
