# Generated by Django 3.2.8 on 2022-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_synchronizedtables_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizedtables',
            name='tables',
            field=models.ManyToManyField(related_name='_core_synchronizedtables_tables_+', to='core.SynchronizedTables', verbose_name='tables'),
        ),
    ]
