# Generated by Django 3.2.8 on 2022-11-09 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_synchronizedtables_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('field_latitude', models.CharField(max_length=255, verbose_name='property latitude')),
                ('field_longitude', models.CharField(max_length=255, verbose_name='property latitude')),
                ('tables', models.ManyToManyField(related_name='markers', to='core.SynchronizedTables', verbose_name='tables')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
