# Generated by Django 3.2.8 on 2022-11-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='synchronizedtables',
            name='markers',
            field=models.ManyToManyField(related_name='markers', to='core.Marker', verbose_name='markers'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='tables',
            field=models.ManyToManyField(to='core.SynchronizedTables', verbose_name='tables'),
        ),
    ]
