# Generated by Django 3.2.8 on 2022-11-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20221109_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchronizedtables',
            name='markers',
        ),
        migrations.AddField(
            model_name='marker',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='core.synchronizedtables', verbose_name='table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marker',
            name='tables',
            field=models.ManyToManyField(related_name='markers_list', to='core.SynchronizedTables', verbose_name='tables'),
        ),
    ]
