# Generated by Django 3.2.8 on 2022-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20221109_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='field_icon',
            field=models.JSONField(default=dict, verbose_name='field icon'),
        ),
        migrations.AddField(
            model_name='marker',
            name='maps_icon',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='maps icon'),
        ),
        migrations.AddField(
            model_name='marker',
            name='type_icon',
            field=models.SmallIntegerField(choices=[(1, 'Url'), (2, 'Campo'), (3, 'Icono Maps')], default=1, verbose_name='type icon'),
        ),
        migrations.AddField(
            model_name='marker',
            name='url_icon',
            field=models.TextField(default=None, null=True, verbose_name='url icon'),
        ),
    ]
