# Generated by Django 3.2.8 on 2023-03-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20221209_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='name',
            field=models.CharField(default='Marcador', max_length=250, verbose_name='name'),
        ),
    ]
