# Generated by Django 3.2.8 on 2023-03-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_marker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='group_by_field',
            field=models.JSONField(default=dict, verbose_name='group by field'),
        ),
    ]
