# Generated by Django 3.2.8 on 2023-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_marker_group_by_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='type_icon',
            field=models.SmallIntegerField(choices=[(1, 'Icono Maps'), (2, 'Campo'), (3, 'Url')], default=1, verbose_name='type icon'),
        ),
    ]
