# Generated by Django 3.2.8 on 2023-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_remove_user_data_groups'),
        ('core', '0037_alter_marker_type_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='tables',
        ),
        migrations.AddField(
            model_name='marker',
            name='data_groups',
            field=models.JSONField(default=list, verbose_name='data groups'),
        ),
        migrations.DeleteModel(
            name='DataGroup',
        ),
    ]
