# Generated by Django 3.2.8 on 2023-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='destination_field',
        ),
        migrations.RemoveField(
            model_name='line',
            name='origen_field',
        ),
        migrations.AddField(
            model_name='line',
            name='field',
            field=models.JSONField(default=dict, verbose_name='line field'),
        ),
    ]
