# Generated by Django 3.2.8 on 2023-06-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20230605_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='destination_marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_lines', to='core.marker', verbose_name='origin marker'),
        ),
        migrations.AlterField(
            model_name='line',
            name='origin_marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_lines', to='core.marker', verbose_name='origin marker'),
        ),
    ]
