# Generated by Django 3.2.8 on 2023-06-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20230605_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.synchronizedtables', verbose_name='table virtual'),
        ),
    ]
