# Generated by Django 3.2.8 on 2023-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_line_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='color',
            field=models.CharField(default=None, max_length=20, verbose_name='line color'),
        ),
    ]
