# Generated by Django 3.2.8 on 2021-10-23 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('description', models.CharField(blank=None, max_length=255, null=True, verbose_name='description')),
                ('type', models.SmallIntegerField(choices=[(0, 'Base de Datos')], default=0, verbose_name='status')),
                ('database_name', models.CharField(blank=None, max_length=255, null=True, verbose_name='database name')),
                ('database_host', models.CharField(blank=None, max_length=255, null=True, verbose_name='database host')),
                ('database_username', models.CharField(blank=None, max_length=255, null=True, verbose_name='database username')),
                ('database_port', models.IntegerField(blank=None, null=True, verbose_name='database port')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
