# Generated by Django 3.2.8 on 2021-10-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='info_to_sync',
            field=models.JSONField(default=dict),
        ),
    ]
