# Generated by Django 3.2.8 on 2021-10-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_connection_info_to_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='database_password',
            field=models.CharField(blank=None, max_length=255, null=True, verbose_name='database password'),
        ),
    ]
