# Generated by Django 3.2.8 on 2021-10-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_connection_database_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='database_host',
            new_name='host',
        ),
    ]
