# Generated by Django 3.2.8 on 2021-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_rename_database_host_connection_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='host',
            field=models.CharField(blank=None, max_length=255, null=True, verbose_name='host connection'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='info_to_sync',
            field=models.JSONField(default=list),
        ),
    ]
