# Generated by Django 3.2.8 on 2021-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20211023_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Base de Datos')], default=0, verbose_name='type'),
        ),
    ]
