# Generated by Django 3.2.8 on 2021-10-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='database_origin',
            field=models.CharField(choices=[('MySQL', 'MySQL')], default='MySQL', max_length=10, verbose_name='database origin'),
        ),
    ]
