# Generated by Django 3.2.8 on 2021-10-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('setting', '0007_connection_database_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='info_to_sync_selected',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='connection',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask', verbose_name='periodic_task'),
        ),
    ]
