# Generated by Django 3.2.8 on 2021-12-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_alter_connection_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='every_interval',
            field=models.IntegerField(blank=None, default=10, verbose_name='every interval'),
        ),
        migrations.AddField(
            model_name='connection',
            name='period_interval',
            field=models.CharField(blank=None, default='seconds', max_length=25, verbose_name='period interval'),
        ),
    ]
