# Generated by Django 3.2.8 on 2021-12-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('setting', '0010_auto_20211202_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.periodictask', verbose_name='periodic task'),
        ),
    ]
