# Generated by Django 3.2.8 on 2022-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_alter_connection_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='database_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='database password'),
        ),
    ]
